### ISSUE TITLE
Problem with elm-json-schema-compilerusage

### ISSUE THREAD

**Issue by samstickland** [NoRedInk/json-elm-schema#32]
Hi,

I've installed elm-json-schema-compiler via Yarn (yarn global add elm-json-schema-compiler), but run I try to run it I get:

```
$ elm-json-schema ./tests/HistoricalStats/Schema.elm
module.js:487
    throw err;
    ^

Error: Cannot find module '/var/folders/wq/74d6rxxx1ggfdj_0vpm656t00000gn/T/1171126-91127-1lv5mth.az3c.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/samuelstickland/.config/yarn/global/node_modules/elm-json-schema-compiler/index.js:23:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

This is with the following Elm file:

```
module HistoricalStats.Schema exposing (dateRangeSchema)

import JsonSchema as JS


dateRangeSchema : JS.Schema
dateRangeSchema =
    JS.object
        [ JS.title "dateRange"
        , JS.properties
            [ JS.required "name" <| JS.string []
            , JS.required "start_date" <| JS.string []
            , JS.required "end_date" <| JS.string []
            ]
        ]
```

I've also tried installing via npm with the same problem.

Any pointers on where I can look for the problem?

**Comment by samstickland** [comment]
I should had mentioned this is on Mac OS X / High Sierra

**Comment by samstickland** [comment]
OK.. I managed to get a little further, and realised that `node-elm-compiler` swallows the errors from `elm-make` (after adding a few `debug` and `verbose` flags to `compiler.compileSync`)

And I wised up and realised that the `Schema` has to be an Elm program that will be compiled and executed, so I added this to the top and bottom of the demo schema above:

```
port module HistoricalStats.Schema exposing (dateRangeSchema)

import JsonSchema.Encoder exposing (EncoderProgram, encodeSchemaProgram)
```

```
main : EncoderProgram
main =
    encodeSchemaProgram statSchema emit


port emit : String -> Cmd a
```

Now I get these error messages:

```
/Users/samuelstickland/development/hubbadoproto/node_modules/elm-json-schema-compiler/index.js:27
var app = Elm.Main.worker()
                  ^

TypeError: Cannot read property 'worker' of undefined
    at Object.<anonymous> (/Users/samuelstickland/development/hubbadoproto/node_modules/elm-json-schema-compiler/index.js:27:19)
```

And once again I don't know how to proceed.

**Comment by jwoudenberg** [comment]
Hey samstickland, sorry for the slow response! The current cli is pretty dumb and assumes the name of the module exporting the program is `Main.elm`. I think if you address that it should work.

**Comment by samstickland** [comment]
Hi @jwoudenberg , Happy New Year!

Would you consider a PR to the CLI based on the changes in this post? 

https://dimiterpetrov.com/blog/keeping-elm-json-decoders-in-sync-with-your-rails-api/

**Comment by jwoudenberg** [comment]
Thanks, happy new year to you too @samstickland!

I'd love a PR based on those changes, looks awesome!
